import type { CSSPropertyGroup } from "./types.js";

/**
 * All editable CSS property groups shown in the visual editor.
 * Each group maps to one tab in the sidebar.
 */
export const CSS_PROPERTY_GROUPS: CSSPropertyGroup[] = [
  {
    id: "colors",
    label: "Colors",
    icon: "🎨",
    properties: [
      {
        id: "background-color",
        label: "Background",
        cssProperty: "background-color",
        type: "color",
        default: "#ffffff",
      },
      {
        id: "color",
        label: "Text color",
        cssProperty: "color",
        type: "color",
        default: "#212121",
      },
      {
        id: "border-color",
        label: "Border color",
        cssProperty: "border-color",
        type: "color",
        default: "#e0e0e0",
      },
    ],
  },
  {
    id: "typography",
    label: "Typography",
    icon: "🔤",
    properties: [
      {
        id: "font-size",
        label: "Font size",
        cssProperty: "font-size",
        type: "range",
        default: "14",
        min: 8,
        max: 36,
        step: 1,
        unit: "px",
      },
      {
        id: "font-weight",
        label: "Font weight",
        cssProperty: "font-weight",
        type: "select",
        default: "400",
        options: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
      },
      {
        id: "letter-spacing",
        label: "Letter spacing",
        cssProperty: "letter-spacing",
        type: "range",
        default: "0",
        min: -2,
        max: 10,
        step: 0.5,
        unit: "px",
      },
      {
        id: "line-height",
        label: "Line height",
        cssProperty: "line-height",
        type: "range",
        default: "1.5",
        min: 0.8,
        max: 3,
        step: 0.1,
        unit: "",
      },
    ],
  },
  {
    id: "spacing",
    label: "Spacing",
    icon: "📐",
    properties: [
      {
        id: "padding",
        label: "Padding",
        cssProperty: "padding",
        type: "range",
        default: "16",
        min: 0,
        max: 64,
        step: 1,
        unit: "px",
      },
      {
        id: "padding-top",
        label: "Padding top",
        cssProperty: "padding-top",
        type: "range",
        default: "16",
        min: 0,
        max: 64,
        step: 1,
        unit: "px",
      },
      {
        id: "padding-right",
        label: "Padding right",
        cssProperty: "padding-right",
        type: "range",
        default: "16",
        min: 0,
        max: 64,
        step: 1,
        unit: "px",
      },
      {
        id: "padding-bottom",
        label: "Padding bottom",
        cssProperty: "padding-bottom",
        type: "range",
        default: "16",
        min: 0,
        max: 64,
        step: 1,
        unit: "px",
      },
      {
        id: "padding-left",
        label: "Padding left",
        cssProperty: "padding-left",
        type: "range",
        default: "16",
        min: 0,
        max: 64,
        step: 1,
        unit: "px",
      },
    ],
  },
  {
    id: "borders",
    label: "Borders",
    icon: "🔲",
    properties: [
      {
        id: "border-radius",
        label: "Border radius",
        cssProperty: "border-radius",
        type: "range",
        default: "12",
        min: 0,
        max: 50,
        step: 1,
        unit: "px",
      },
      {
        id: "border-width",
        label: "Border width",
        cssProperty: "border-width",
        type: "range",
        default: "0",
        min: 0,
        max: 10,
        step: 1,
        unit: "px",
      },
      {
        id: "border-style",
        label: "Border style",
        cssProperty: "border-style",
        type: "select",
        default: "none",
        options: ["none", "solid", "dashed", "dotted", "double", "groove", "ridge"],
      },
    ],
  },
  {
    id: "effects",
    label: "Effects",
    icon: "✨",
    properties: [
      {
        id: "opacity",
        label: "Opacity",
        cssProperty: "opacity",
        type: "range",
        default: "1",
        min: 0,
        max: 1,
        step: 0.05,
        unit: "",
      },
      {
        id: "box-shadow",
        label: "Box shadow",
        cssProperty: "box-shadow",
        type: "select",
        default: "none",
        options: [
          "none",
          "0 1px 3px rgba(0,0,0,0.12)",
          "0 2px 6px rgba(0,0,0,0.15)",
          "0 4px 12px rgba(0,0,0,0.15)",
          "0 8px 24px rgba(0,0,0,0.15)",
          "0 16px 40px rgba(0,0,0,0.2)",
          "inset 0 1px 3px rgba(0,0,0,0.12)",
        ],
      },
      {
        id: "transition",
        label: "Transition",
        cssProperty: "transition",
        type: "select",
        default: "none",
        options: [
          "none",
          "all 0.2s ease",
          "all 0.3s ease",
          "all 0.5s ease",
          "background-color 0.3s ease",
          "box-shadow 0.3s ease",
        ],
      },
      {
        id: "filter",
        label: "Filter",
        cssProperty: "filter",
        type: "select",
        default: "none",
        options: [
          "none",
          "brightness(0.9)",
          "brightness(1.1)",
          "contrast(1.1)",
          "saturate(1.2)",
          "grayscale(0.5)",
          "grayscale(1)",
          "sepia(0.3)",
        ],
      },
    ],
  },
];
